`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

<!--
If you feel it necessary to include an appendix, it goes here.
-->




# Appendix A{#appendix .unnumbered}

**KPSS Test**
https://www.rdocumentation.org/packages/tseries/versions/0.10-46/topics/kpss.test
(Insert table of KPSS test results - before and after differencing)
	
**Data Cleansing**
Scholle IPN Data
The Scholle IPN data provides a variety of relevant data features that uninformed users can use to gain knowledge about Scholle IPN’s product.  Our team will use this data to find relevant trends that may be useful in forecasting.  The table below describes the Scholle IPN metadata:

Prior to searching for any relevant patterns in the Scholle IPN data, it is best practice to conduct preliminary data cleansing.  First, we notice that there are 8,204 total orders in this dataset ranging from a delivery date of 10/1/2009 to 11/2/2018.  It is important to note that this dataset is a combination of orders from all of Scholle IPN clients in their syrup bag product line.  Of all the orders, 5,118 of the records lists ‘Coca-Cola’ as the top business partner.  Other issues include null values being present for the ‘Ship_to_State’ variable and negative values for ‘quantity’ variable.

The following data cleansing steps were conducted to prepare the Scholle IPN data for monthly aggregation:
*Filter syrup bag orders for ‘Coca-Cola’ top business partner.  
*Drop records with quantities of less than one thousand.  
*Impute records with missing values in ‘Ship_to_State’ with ‘Bayamon, PR’.
*Drop records outside of the United States and Canada market.
*Drop records that occurred after October 2018.  

Once the steps listed have been conducted, the primary data is left with only 4,875 records.  The final step to data cleansing will be aggregating the records at the monthly level.  The ‘Planned Delivery Date’ field will be used to aggregate quantities at the desired level.  

**Twitter Data Collection**
The selected terms (Coca-Cola, Pepsi, McDonald’s, Taco Bell, Jobs) will be used to collect user-generated tweets.  The collection of this data will be done by using Twitter’s Search API.  Twitter posts containing  the terms ‘coke’, ‘pepsi’, ‘mcdonalds’, ‘taco bell’, or ‘jobs’ will be collected from the 15th of every month from July 2009 to December 2018.  Twitter’s Search API impose strict restrictions on query results depending on the account level purchased. For this project, a maximum of 500 user-generated tweets will be collected per month in the given date range. For example, for the month of December 2018, there will be 500 tweets collected related to Coca-Cola, Pepsi, McDonald’s, Taco Bell, and jobs.  This means that at any given month, the distribution of tweets across different terms can differ depending on what search term is trending. 

Since this project is concerned with the US and Canada markets, we need to add a series of Search API query constraints to ensure that collected tweets are mainly from users in these selected markets.  The first constraint was to query results in the english language by filtering for user profiles with country codes of ‘us’ or ‘ca’. The second constraint involves the time of day that the tweets were posted.  Since Twitter Search API collects tweets in reverse chronological order given a date and time, a time constraint of 23:00 UTC (6 pm CST) was applied to the queries to ensure that collected tweets will fall in a time range when most people in the US and Canada are off normal working hours.  This will provide a robust collection of tweets from a variety of different users across different regions of the US and Canada.  The final output of these Twitter search queries will include the tweet content, tweet date and time, number of replies, number of retweets, and number of likes. 

The second approach to collecting Twitter data is to gather historical Twitter posts generated by the official Twitter accounts of Coca-Cola, Pepsi, McDonald’s, and Taco Bell from July 2009 to December 2018 using a separate web scraping tool. These selected Twitter accounts vary greatly in their online activity.  While some accounts, like Taco Bell, reply frequently to their followers, other accounts tend to be less engaging and post infrequently.  For the purpose of this project, only independent tweets posted by each Twitter account will be collected. This means that tweet replies to Twitter users will not be collected.  The main benefit of this approach is that it allows us to focus on tweets that promote individual marketing campaigns.  The final output of this data collection step will include tweet content, tweet date and time, number of replies, number of retweets, and number of likes.  
The total output of the Twitter data collection results are 56,528 user-generated tweets and 24,442 company-generated tweets from July 2009 to December 2018.  For both datasets, tweets outside of October 2009 to October 2018 will be filtered out to prepare for time series modeling. 

The user-generated tweets will require additional pre-processing steps prior to monthly aggregation. The Twitter Search API collects tweets on a rule-based approach meaning it is probable that nonsensical tweets may be included in the raw data collected. For example, tweets referencing the drug ‘cocaine’ (or ‘coke’ in colloquial terms) were identified in the raw data.   A series of natural language processing steps were conducted on the tweet’s text to help screen out these “noisy“ tweets.  In addition, these steps will be important to prepare the tweet data for aggregation.  Some of these processing steps include removing stopwords, creating n-grams, and tokenizing text.  After conducting text processing steps, an R package was used to calculate the sentiment of a given tweet.  This step will provide us with an additional feature that will inform business users about user sentiment on their product.  After these pre-processing steps, the tweets will now be aggregated on a monthly level to generate the following independent variables for each search term (Coca-Cola, Pepsi, McDonald’s, Taco Bell, “Jobs”): total tweets per month, total replies per month, total likes per month, total retweets per month, and average sentiment per month.  There are a total of 25 variables generated from this step.
The company-generated tweets from Coca-Cola, Pepsi, McDonald’s, and Taco Bell will be aggregated on a monthly level to generate the following independent variables for each Twitter account (Coca-Cola, Pepsi, McDonald’s and Taco Bell): total tweets per month, total replies per month, total likes per month, total retweets per month.  There are a total 16 variables generated from this step.

**Google Trends Data**
Google Trends data will also be collected to better anticipate the demand for Coca-Cola products.  Although Google Trends is not a social media platform, it does provide its users with quantified information about the relative popularity of a search term over time.  The monthly Google Trend values for the following terms will be collected: Coca-Cola, Pepsi, McDonald’s, Taco Bell, and ‘Jobs’.  Each topic will be queried individually with the date range October 2009 to October 2018.  Google Trend values for each term will range between 0 to 100, with 100 signifying the month in which the term was most popular.  No additional preprocessing is required for Google Trends data.  There are a total of five variables generated from this step.

**Exploratory Data Analysis - Scholle IPN**
The maximum quantity of bags ordered occurred in November 2011 with a total of 13,685,000 bag orders, while the minimum quantity of bags ordered occurred in January 2011 with a total of 5,215,810 bag orders.  After exploring the Scholle IPN data, it was also observed that the Columbus (OH), Atlanta (GA), and Dallas (TX) are the top cities where Coca-Cola bag orders were being delivered.  Given that information, it is less surprising to observe that the top three states by quantity of bag order deliveries were Ohio, Georgia, and Texas.  In terms of Coca-Cola bag products, the stock-keeping unit (SKU) 200258 and 200144 were the two most ordered SKU.

**Exploratory Data Analysis - Social Media Variables**
Similar to the Scholle IPN data, it is important to explore our covariates to identify any underlying trends that could be used to forecast Coca-Cola demand.  For user-generated tweets, a total of 52,952 user-generated tweets were collected between October 2009 to October 2018.  Among the four companies, McDonald’s is the most talked about company over the given date range.  When exploring which terms appear the most with each other, the term that appeared most commonly with Coca-Cola is Pepsi.

**Sentiment Analysis**
https://github.com/trinker/sentimentr

