---
author: 'Elijah Ampo, Ruohan Zhou, and Yingkun Zhu'
date: 'May, 2019'
institution: 'University of Chicago'
division: 'Graham School'
advisor: 'Arnab Bose'
altadvisor: 'Dr. Sema Barlas'
department: 'Continuing Liberal and Professional Studies'
degree: 'Master of Science in Analytics'
title: 'Forecasting Manufacturing Orders Using Social Media'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  phoenixdown::capstone_pdf: default
#  phoenixdown::capstone_gitbook: default
#  phoenixdown::capstone_word: default
#  phoenixdown::capstone_epub: default
#
# If you are creating a PDF you'll need to write your preliminary content as well as define some other parameters below.
abstract: | 
  `r if(knitr:::is_latex_output()) paste(readLines("00--abstract.Rmd"), collapse = '\n  ')` 
executive: |  
  `r if(knitr:::is_latex_output()) paste(readLines("00--executive-summary.Rmd"), collapse = '\n  ')` 
#
# Longer preliminary content, like the Abstract and Executive Summary above, is best organized in seperate files.
# The inline r function is used above to paste the contents of those files, instead of requiring you one to type 
# lengthy text directly into the yaml header. For shorter messages, typing directly into the YAML is easier. See below.
# VERY IMPORTANT: A tab indent is needed on the line following the | .
#
#preface: |
#  A preface is OPTIONAL. Use a preface if you want to explain your interest in the report topic and include anything about your #experience that readers should keep in mind. If you would rather not include a preface, comment it out or delete it from the YAML header #of the index.Rmd file.
#
#acknowledgements: |
#  I want to thank a few people.
#dedication: |
#  You can have a dedication here if you wish.
#
# Download your specific bibliography database file, place it in the "bib" folder, and refer to it in the line below
bibliography: bib/thesis.bib
#
# To change your Citation Style Language file, you can do so below. Though the default is apa style.
csl: csl/apa.csl
lot: true
lof: true
#
# Add a "#" at the beginning of the following line if you'd like remove space between parapgraphs.
space_between_paragraphs: true
#
# Dimensions below correspond to University of Chicago Masters of Science in Analytics requirements.
geometry: "left=3.8cm, right=2.5cm, top=2.5cm, bottom=2.5cm"
#
  #header-includes:
#- \usepackage{tikz}
---



<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Preface for example, simply delete lines 32-33 above or add a "#"" before them to comment out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this:
-->

<!--

If you receive a duplicate label error after knitting, delete the extra .Rmd file and then knit again.
-->

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for PDF files and also delete the # before rmd_files: there. Do not include 00(two-hyphens)prelim.Rmd,  00(two-hyphens)abstract.Rmd and 00(two-hyphens)executive summary.Rmdsince they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters, which is the standard for each section.
-->

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
```

# Introduction {.unnumbered}

Scholle IPN is a global manufacturing company based in Northlake, IL, with products focused primarily in bag-in-box packaging. The company is a pioneer in its industry by implementing a combination of qualitative observations and quantitative analyses in forecasting their products’ sales.  However, variability in these sales forecasts present challenges for Scholle IPN in raw material preparation, operational efficiency, and asset management.
        
## Problem Statement {.unnumbered}

In this project, we will provide a forecasting solution to Scholle IPN using social media data.  This project will primarily focus on one of Scholle IPN’s main clients, Coca-Cola.    Coca-Cola uses Scholle IPN’s state-of-the art bags to store beverage products at quick service restaurant (QSR) partners worldwide.  Since 2014, Coca-Cola has accounted for 95.68% of Scholle’s syrup-related bag order shipments, so inaccurate forecasts of future orders could result in operational inefficiencies.  Minimizing these operational inefficiencies is important to maintain Scholle’s partnership with Coca-Cola.  In order to solve this business problem, we will examine whether we can substantially improve Scholle IPN’s Coca-Cola demand forecasts by using social media as the primary variable.


## Research Purpose {.unnumbered}

The purpose of this research is to forecast Coca-Cola bag orders by utilizing social media data.  When customer express their opinions in social media, businesses like Scholle IPN can gain valuable insights that can inform business decisions.  For example, if a McDonald’s promotion is generating discussion posts online, then Scholle IPN can potentially expect an increase in bag orders from Coca-Cola.  In order to make these online discussions actionable, we must first take into account additional considerations.  First, since social media posts are usually in the form of text, we will explore methods to convert text to numerical data.  Second, we will need to explore different ways to reduce the dimension of social media variables to account for its high dimensionality.  And finally, we will use these social media variables to forecast Coca-Cola bag orders using an ensemble approach.  Below is a list of research objectives for this project:

* Convert text-based social media data to numerical data using natural language processing.
* Reduce the dimension of social media variables using different methods.
* Forecast Coca-Cola bag orders using an ensemble approach.

## Variables and Scope {.unnumbered}

The scope of this forecasting project will be limited to predicting the future monthly bag orders for Coca-Cola in the United States and Canada.  All variables will be aggregated or averaged at the monthly level.  The forecasting window for this project will be 18 months for all models to accommodate Scholle’s business needs.  The main social media variables used to predict Coca-Cola bag orders will be collected from Twitter and Google Trends.  For Twitter, we will focus our project on the following variables: tweet text, number of likes, number of retweets, and number of replies.  For Google Trends, monthly trend values for selected topics will be extracted at the monthly level.  Additional data retrieval rules were applied to ensure that Twitter and Google Trends data are from the United States and Canada (see Appendix A).

## Writing Tips {.unnumbered}

* Develop an outline of what you are going to write for each section before you start writing
* Good writing follows a general format: introduction, body, and conclusion. This rule applies to the entire project, to each section, and to each paragraph
* Each paragraph presents only one idea and follows the **MEAL** rule
    + **M**ain: start the paragraph with the _Main_ idea
    + **E**xplain the concepts and define the terms
    + **A**nalyze the idea
    + **L**ink: conclude the paragraph and _Link_ it to the next paragraph 
* Make sure to define any concepts or terms that reader might be unfamiliar with right before or after they are used

**More info**

And here's some other random info: the first paragraph after a chapter title or section head _shouldn't be_ indented, because indents are to tell the reader that you're starting a new paragraph. Since that's obvious after a chapter or section title, proper typesetting doesn't add an indent there. 

**Spacing and Markdown**

Be careful with your spacing in _Markdown_ documents.  While white-space largely is ignored, it does at times give _Markdown_ signals as to how to proceed.  As a habit, try to keep everything left aligned whenever possible, especially as you type a new paragraph.  In other words, there is no need to indent basic text in the Rmd document (in fact, it might cause your text to do funny things if you do).




### Line breaks {.unnumbered}

Make sure to add white space between lines if you'd like to start a new paragraph.  Look at what happens below in the outputted document if you don't:

Here is the first sentence.  Here is another sentence.  Here is the last sentence to end the paragraph.
This should be a new paragraph.

*Now for the correct way:* 

Here is the first sentence.  Here is another sentence.  Here is the last sentence to end the paragraph.

This should be a new paragraph.



